### ISSUE TITLE
Xenia metacell analysis files

### ISSUE THREAD

**Issue by wathmih** [sebepedroslab/Stylophora_single_cell_atlas#5]
Thank you for the detailed scripts for the analysis. I am wanting to reproduce the analysis of the Xenia data using 06_Metacell_Xenia.Rmd and I need some help with a few areas: 

I had a look at the folders, but unfortunately, I was not able to find the initial import file with the expression data named '10x_import_table.txt'. Could you please let me know where I could find this file?  

Then, in the input data filtering part, the following code is presented: kill_nowholev2=setdiff(colnames(mat_nowholev2@mat),orig_cell_names), but I cannot seem to find 'orig_cell_names'. And when I enter the code, it says that it cannot find 'orig_cell_names' object. I am not too sure if this is a file that I am suppose to import, but cannot seem to find. I don't quite understand, could you please let me know what I should do here? 

Also, for calculating gene statistics, the following code is shown: mcell_add_gene_stat(gstat_id = "gstat", mat_id = mat_nm_filt, force = TRUE), however I cannot seem to find 'mat_nm_filt'. Same as before, I am not too sure if this is a file I need to import or if I am suppose to do something else here, could you please let me know? 

I would really appreciate it if you could please help me with this. 

Thank you! 
Wathmi

**Comment by anamariaelek** [comment]
Hi Wathmi, thak you for pointing these things out, I will try to explain in details what is going on here.

This file `10x_import_table.txt` is used to import Cell Ranger output matrix as metacell matrix object in R. This file was not present because it points to Cell Ranger output (`/users/asebe/asebe/proj/scRNA_xenia/Cellranger/`) which is not included in this repository because of its size. As described in the [Methods section](https://www.cell.com/cell/fulltext/S0092-8674(21)00440-2?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0092867421004402%3Fshowall%3Dtrue#secsectitle0075), we did this by running CellRanger with `–force-cells = 50000`. We also discarded the whole organism 10x v2 dataset because we detected strong batch effect in it, and this is where `orig_cell_names` comes from. Initially we did clustering with all cells and filtered out cell names from discarded dataset, but this is better done by not including this matrix during import, i.e. in `10x_import_table.txt`, in which case the filtering step is redundant. I uploaded `10x_import_table.txt` now for the sake of completeness and modified the code snippet to indicate this.
Finally, `mat_nm_filt` is a name of matrix object after filtering, (`mat_nowholev2`), and by mistake it was not defined because I passed it to filtering function directly (`mcell_mat_ignore_cells`,`mcell_mat_ignore_genes`). Thank you for spotting this inconsistency.

If you are interested in reproducing the entire analysis, you would need to first re-process raw reads from the original publication (https://www.nature.com/articles/s41586-020-2385-7#data-availability). 
However, if you only want to reproduce the metacell analysis in this notebook, you can directly load the metacell UMI matrix with `mat_nowholev2 <- scdb_mat("mat_nowholev2")`.

Hope this clears things up.

**Comment by wathmih** [comment]
> 

Thank you very much for clearing these areas up for me! This all makes sense now :) 

Kind regards, 
Wathmi
