### ISSUE TITLE
Metacell Xenia- annotation correlations

### ISSUE THREAD

**Issue by Cuneyt-C** [sebepedroslab/Stylophora_single_cell_atlas#6]
Hi!

I am also trying to reproduce your Xenia metacell analysis. However, I have encountered an issue with the functions used here which I am not able to solve. In the section "annotation correlations" you are using var_genes (Nvec identifiers) as input for "markers". I believe there is a problem, as in the sca_clustering_correlation function, the input matrices are then being subsetted using this list of markers. For mc@mc_fp (Xenia dataset), subsetting it with the Nvec identifiers is returning "character (0)" so therefore the cor() function returns an error message. I am wondering if I am doing something wrong or whether there is a step missing in the script. I tried to find the matching Xenia Ids in the file "Nvec_Xesp_og_pairs.txt" that you have provided but there are multiple matches for some orthologues. How did you exactly process the data here? Appreciate your help.

Thank you!

Cuneyt

**Comment by Cuneyt-C** [comment]
I am sorry, I have a few more questions:
The following section is "Save cell and metacell annotations": It is not clear to me how to get "mc_filt" - this seems to be added further below? Also, while I think the required Xenia annotation files are the ones uploaded here ("Xesp_cell_type_annotation" and "Xesp_metacell_annotation"), I am not sure how "cell_annotation" has been generated.

Sorry for being such trouble :)

Cuneyt

**Comment by anamariaelek** [comment]
Hi Cuneyt, thanks for taking interest in reproducing this analysis. Indeed, there are some pieces of code missing, mostly because I was putting this notebook together from several scripts. Sorry about that.

Regarding your first question, the _Xenia_ annotations were done after replacing gene names with _Nematostella_ orthologs, otherwise this function would not work, as you point out. For multiple orthologs, I duplicated entries in the table as necessary. In the downstream comparisons I used dedicated cross-species functions, where these things are handled internally, however, for the initial annotation step here, this was not implemented yet.

Regarding your second question, `mc_filt` is the final filtered metacell solution, it is generated at the end of this section, but as I was doing this step several times iteratively, it ended up as an starting point, too. It should be `mc_kill` there initially. I updated the notebook now.

 Again, for convenience, and reproducibility of downstream analyses, I uploaded final metacell objects and annotations to this repository.
